language: node_js
node_js:
  - "6"
env:
 - CXX=g++-4.8
addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-4.8
     - gcc-4.8
before_script:
  - npm install
script: npm test
notifications:
 slack:
   secure: ft7AczZfcT02IoTPCagJThYRFN+9naSHgmKSW8Ac2u6Dno2X2TR/SDW3yMEn/XoOxzGB7ukhodkp1I5V8s606wpCz1nC2MjkSqxoMdxZfWxrOMGALDLeBx+KxA4mFKlicOae4KezuugKz4+KjnUjv0vDUfAKH7LyYeKaSc8ZSNnPzxMuroqb/BQ8xex0SXZmE/MEetcbHseOwPs6q/g+lLCHHwS+Fn6R6UjY6I6JUeSn70MR/g7oWDdXj57OfqIKA98oywKxwuw9vgIHFSbv50fJaSN5jwHWaxt0Zar3kuBTHgarBJrznDqUsv/h7itbJYS9ky+Wx0B74TTaSCtz+alJOpLjt8EA6PiLj6nIUeNTtdaDAOxBVrKgwKv7hO7rNHnFPUTb4HUhp6s3rRQ2dH4wUGm0aFwIUUFBVP5FnW36Kow/WlU6S7Y8aqX/kepvmdYd8pwE6UUDXqtzyeczctiSh8WPnmGuP+ocWyVTqfwYOna5iVHJfwWst4R67QfqgPNxUvapWRq+QKq7DB4WtUNVTG1Mws/ZUie3IcpYH0K+2FyU1jRPTU24F8gRgwPGM8bodl08meM1YwRrObONz4OGyK/OfX68M3yUIUGIH7BB6lLwsPDtKuhXcYWAgeDBIYAf4fM4Hp22D3Dfjsgf1qv5bxVnotHkNNAl9QcVUCw=
